prompt CREATE_TABLE_MGNF_LOGICAL_SEGMENTS.sql
@CREATE_TABLE_MGNF_LOGICAL_SEGMENTS.sql

prompt CREATE_TABLE_MGNF_TEST_RECORDS.sql
@CREATE_TABLE_MGNF_TEST_RECORDS.sql

prompt T_MGNF_FRAG.tps
@T_MGNF_FRAG.tps

prompt T_MGNF_FRAGS.tps
@T_MGNF_FRAGS.tps

prompt MAGNIFIER.pkg
@MAGNIFIER.pkg
