CREATE OR REPLACE TYPE T_MGNF_FRAG IS OBJECT
(
	BEGIN_POS  INTEGER,
	END_POS    INTEGER,
	FRAG_LEVEL INTEGER,
	FRAG_TEXT  VARCHAR2(4000)
)
/

CREATE OR REPLACE TYPE T_MGNF_FRAGS IS TABLE OF T_MGNF_FRAG
/
