WITH VC AS
 (SELECT V.*,
         LAG(V.FRAG_LEVEL, 1) OVER(ORDER BY NULL) LAST_LEVEL,
         LAG(V.FRAG_TYPE, 1) OVER(ORDER BY NULL) LAST_TYPE
    FROM TABLE(MAGNIFIER.SPLIT_FRAGMENTS('SELECT * FROM DEMO_A A, DEMO_B B WHERE V.B_WORD  = V.A_WORD ( + )')) V),
VD AS
 (SELECT V.*,
         CASE
           WHEN V.FRAG_LEVEL != NVL(V.LAST_LEVEL, 0) THEN
            V.BEGIN_POS
           ELSE
            NULL
         END LEVEL_SHIFT
    FROM VC V),
VE AS
 (SELECT V.BEGIN_POS,
         V.END_POS,
         V.FRAG_LEVEL,
         V.FRAG_TYPE,
         V.FRAG_TEXT,
         V.LEVEL_SHIFT,
         CASE
           WHEN V.FRAG_TYPE != NVL(V.LAST_TYPE, ' ') THEN
            V.BEGIN_POS
           WHEN V.LEVEL_SHIFT IS NOT NULL THEN
            V.LEVEL_SHIFT
           ELSE
            NULL
         END SEG_SHIFT
    FROM VD V),
VF AS
 (SELECT V.*,
         MAX(V.LEVEL_SHIFT) OVER(ORDER BY NULL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LEVEL_GROUP,
         MAX(V.SEG_SHIFT) OVER(ORDER BY NULL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) SEG_GROUP,
         SUM(CASE
               WHEN V.FRAG_TYPE IN
                    ('SELECT', 'INSERT', 'DELETE', 'UPDATE', 'MERGE') THEN
                1
               ELSE
                0
             END) OVER(PARTITION BY NULL) QUERY_DML
    FROM VE V),
VG AS
 (SELECT V.BEGIN_POS,
         V.END_POS,
         V.FRAG_LEVEL,
         V.FRAG_TYPE,
         V.FRAG_TEXT,
         V.SEG_GROUP,
         CASE
           WHEN UPPER(V.FRAG_TEXT) IN ('WHERE', 'ON', 'HAVING', 'AND', 'OR') THEN
            V.BEGIN_POS
           ELSE
            NULL
         END LOGIC_SHIFT
    FROM VF V
   WHERE V.QUERY_DML > 0
     AND V.FRAG_TYPE IN ('WHERE', 'ON', 'HAVING')
     AND V.FRAG_TEXT NOT IN ('(', ')')),
VH AS
 (SELECT V.*,
         MAX(V.LOGIC_SHIFT) OVER(ORDER BY NULL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LOGIC_GROUP
    FROM VG V)
SELECT MIN(V.BEGIN_POS) BEGIN_POS,
       MAX(V.END_POS) END_POS,
       V.FRAG_LEVEL,
       V.FRAG_TYPE
  FROM VH V
 WHERE V.LOGIC_SHIFT IS NULL
 GROUP BY V.LOGIC_GROUP, V.FRAG_LEVEL, V.FRAG_TYPE
 ORDER BY V.LOGIC_GROUP
