WITH VA AS
 (SELECT V.*,
				 LAG(V.FRAG_LEVEL, 1) OVER(ORDER BY NULL) LAST_LEVEL,
				 LAG(V.FRAG_TYPE, 1) OVER(ORDER BY NULL) LAST_TYPE
		FROM TABLE(MAGNIFIER.SPLIT_FRAGMENTS('select "DUMMY", 1 from (select * from dual where 1=2)A,DUAL T where (2=3 or (3>2)) ORDER BY 1')) V),
VB AS
 (SELECT A.*,
				 CASE
					 WHEN A.FRAG_LEVEL != NVL(A.LAST_LEVEL, 0) THEN
						A.BEGIN_POS
					 ELSE
						NULL
				 END LEVEL_SHIFT
		FROM VA A),
VC AS
 (SELECT B.BEGIN_POS,
				 B.END_POS,
				 B.FRAG_LEVEL,
				 B.FRAG_TYPE,
				 B.FRAG_TEXT,
				 B.LEVEL_SHIFT,
				 CASE
					 WHEN B.FRAG_TYPE != NVL(B.LAST_TYPE, ' ') THEN
						B.BEGIN_POS
					 WHEN B.LEVEL_SHIFT IS NOT NULL THEN
						B.LEVEL_SHIFT
					 ELSE
						NULL
				 END SEG_SHIFT
		FROM VB B),
VD AS
 (SELECT C.*,
				 MAX(C.LEVEL_SHIFT) OVER(ORDER BY NULL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LEVEL_GROUP,
				 MAX(C.SEG_SHIFT) OVER(ORDER BY NULL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) SEG_GROUP
		FROM VC C),
VE AS
 (SELECT D.BEGIN_POS,
				 D.END_POS,
				 D.SEG_GROUP,
				 D.FRAG_TEXT,
				 CASE
					 WHEN UPPER(D.FRAG_TEXT) IN ('WHERE', 'ON', 'HAVING', 'AND', 'OR') THEN
						D.BEGIN_POS
					 ELSE
						NULL
				 END LOGIC_SHIFT
		FROM VD D
	 WHERE D.FRAG_TYPE IN ('WHERE', 'ON', 'HAVING')
		 AND D.FRAG_TEXT NOT IN ('(', ')')),
VF AS
 (SELECT E.*,
				 MAX(E.LOGIC_SHIFT) OVER(ORDER BY NULL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) LOGIC_GROUP
		FROM VE E)
SELECT MIN(F.BEGIN_POS) BEGIN_POS,
			 MAX(F.END_POS) END_POS,
			 LISTAGG(F.FRAG_TEXT, '') WITHIN GROUP(ORDER BY F.BEGIN_POS)
	FROM VF F
 WHERE F.LOGIC_SHIFT IS NULL
 GROUP BY F.LOGIC_GROUP
