SELECT SUBSTR('SELECT T.*
	FROM JDL_TEST_PART T
 WHERE T.GRP = 3
		OR T.RNK = 2',
							L.LOGIC_ID,
							L.LOGIC_END - L.LOGIC_ID + 1) LOGIC,
			 CASE
				 WHEN R.RUN_ID IS NOT NULL THEN
					'COVERED'
				 ELSE
					'UNCOVER'
			 END COVER
	FROM MGNF_LOGICAL_CLAUSES L
	LEFT JOIN MGNF_TEST_RECORDS R
		ON L.USER_ID = R.USER_ID
	 AND L.PROGRAM = R.PROGRAM
	 AND L.LINE_ID = R.LINE_ID
	 AND L.SIGN_ID = R.SIGN_ID
	 AND L.LOGIC_ID = R.LOGIC_ID
 ORDER BY L.LOGIC_ID